# Predict iris species for a given set of input parameters
POST http://localhost:8000/predict
Content-Type: application/json

{
    "sepal_length": 5.1,
    "sepal_width": 3.5,
    "petal_length": 1.4,
    "petal_width": 0.2
}
